using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("Horn.Core.Spec for Microsoft .NET Framework 3.5")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyCompanyAttribute("Horn")]
[assembly: AssemblyProductAttribute("Horn.Core.Spec")]
[assembly: AssemblyCopyrightAttribute("ncontinuity2 Project, original author or authors")]
[assembly: AssemblyVersionAttribute("2.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("2.0.0.0")]
[assembly: AssemblyFileVersionAttribute("2.0.0.0")]
[assembly: AssemblyDelaySignAttribute(false)]

